name: Deploy React App to Server with Bun

on: 
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # Enables emulation for multi-platform builds (e.g., linux/amd64, linux/arm64)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Sets up Buildx for building multi-architecture images

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # Authenticates with GHCR using the default GitHub token

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        # Extracts metadata like tags and labels based on GitHub event

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./patroni-node
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64 # Multi-platform build
          push: ${{ github.event_name != 'pull_request' }} # Only push on main branch or tags
          tags: "node"
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        # Builds and pushes the image to GHCR with caching
